name: Generate shadowrocket rules from sing-box rulesets

run-name: ${{ github.actor }} is building shadowrocket rules 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4        

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/russia-v2ray-rules-dat
          ref: refs/heads/release
          path: russia-v2ray-rules-dat
        
      - name: Copy source files to dir
        run: |
          mkdir ./singbox-rules
          cp -r ./russia-v2ray-rules-dat/sing-box/rule-set-geosite/. ./singbox-rules/
          ls ./singbox-rules/

      # - name: List files in workdir
      #   run: |
      #     ls ${{ github.workspace }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # You can test by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: install sing-box
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.10.7/sing-box-1.10.7-linux-amd64.tar.gz
          tar -xvzf sing-box-1.10.7-linux-amd64.tar.gz
          ./sing-box-1.10.7-linux-amd64/sing-box -h
        # bash <(curl -fsSL https://sing-box.app/deb-install.sh)        

      - name: run parser
        run: python3 parse.py

      - name: check results and generate zip
        run: |
          cd shadowrocket-rules/
          ls | wc
          zip -r ../shadowrocket-rules.zip *

      - name: Загружаем zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadowrocket_zip
          path: ./shadowrocket-rules.zip
          retention-days: 1

      - name: Загружаем artifact 
        uses: actions/upload-artifact@v4
        with:
          name: shadowrocket-rules
          path: ./shadowrocket-rules/ # or path/to/artifact
          retention-days: 1

  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build_rules
    steps:   
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          mkdir -p github_release
        shell: bash

      - name: Скачиваем zip artifact 
        uses: actions/download-artifact@v4
        with:
          name: shadowrocket_zip
          path: ./github_release/
    
      - name: Публикуем zip artifact в releases
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./github_release/shadowrocket-rules.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup
        run: |
          rm -rf ./github_release/
          mkdir -p publish

      - name: Скачиваем artifact 
        uses: actions/download-artifact@v4
        with:
          name: shadowrocket-rules
          path: ./publish/rules/

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

  Delete_Historical_Data:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      actions: write
      contents: read
    steps:
        - name: Delete old artifacts
          uses: geekyeggo/delete-artifact@v5
          with:
            name: |
                shadowrocket-rules
                shadowrocket_zip

        - name: Удаляем старые теги и релизы
          uses: dev-drprasad/delete-older-releases@v0.3.4
          with:
            keep_latest: 5
            delete_expired_data: 7
            delete_tags: true
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Удаляем старый workflow
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 7
            keep_minimum_runs: 3
